---

# client.nfs
# ----------
- src: cmprescott.autofs

# client.media
# ------------
- src: cmprescott.kodi
- src: cmprescott.mc2xml
- src: cmprescott.tvheadend
- src: cmprescott.HDHomeRun

# server.*
# --------
- src: cmprescott.common
- src: geerlingguy.mysql
- src: geerlingguy.php
  version: 1.9.1
- src: jdauphant.nginx

# server.media
# -----------
- src: MichaelRigart.mount
- src: geerlingguy.nfs

# server.router
# -------------
- src: cmprescott.dnsmasq
- src: cmprescott.FireHOL
- src: debops.ifupdown

# server.torrent
# --------------
- src: cmprescott.rTorrent
- src: cmprescott.ruTorrent
- src: cmprescott.jre
- src: cmprescott.FileBot

# server.wordpress
# ----------------
- src: heskethm.wp-cli

...