---

# client.media
# ------------
- src: cmprescott.kodi
- src: cmprescott.mc2xml
- src: cmprescott.tvheadend
- src: cmprescott.HDHomeRun

# server.*
# --------
- src: cmprescott.common

# server.media
# -----------
- src: MichaelRigart.mount
- src: geerlingguy.nfs
- src: geerlingguy.mysql

# server.router
# -------------
- src: cmprescott.dnsmasq
- src: cmprescott.FireHOL
- src: debops.ifupdown

# server.torrent
# --------------
- src: cmprescott.rTorrent
- src: cmprescott.ruTorrent
- src: geerlingguy.php
- src: jdauphant.nginx
- src: cmprescott.jre
- src: cmprescott.FileBot

...