# .requirements.yml
---
# client.nfs
# ----------
- src: cmprescott.autofs

# client.torrent
# --------------
- src: cmprescott.common
- src: cmprescott.rTorrent
- src: cmprescott.jre
- src: cmprescott.FileBot

# server.*
# --------
- src: geerlingguy.php

# server.jenkins
# --------
- name: "ansible-role-jenkins"
  src: geerlingguy.jenkins
- name: "ansible-role-nginx"
  src: jdauphant.nginx
- name: "ansible-role-ssl-certs"
  src: jdauphant.ssl-certs

# server.torrent
# --------------
- src: cmprescott.ruTorrent

# server.wordpress
# ----------------
- src: geerlingguy.mysql
- src: heskethm.wp-cli

...