---

# client.nfs
# ----------
- src: cmprescott.autofs

# client.torrent
# --------------
- src: cmprescott.common
- src: cmprescott.rTorrent
- src: cmprescott.jre
- src: cmprescott.FileBot

# server.*
# --------
- src: geerlingguy.php
- src: jdauphant.nginx

# server.torrent
# --------------
- src: cmprescott.ruTorrent

# server.wordpress
# ----------------
- src: geerlingguy.mysql
- src: heskethm.wp-cli

...