---

# *.*
# --------
- src: cmprescott.common

# client.developer
# ------------
- src: cmprescott.jre
- src: cmprescott.SmartGit

# client.media
# ------------
- src: cmprescott.kodi

# server.media
# -----------
- src: MichaelRigart.mount
- src: geerlingguy.nfs
- src: geerlingguy.mysql

# server.router
# -------------
- src: cmprescott.dnsmasq
- src: cmprescott.FireHOL
- src: debops.ifupdown

# server.torrent
# --------------
- src: cmprescott.rTorrent
- src: cmprescott.ruTorrent
- src: geerlingguy.php
- src: jdauphant.nginx

...