---

- name: "Developer Client"

  hosts: clients.developer

  vars: {}

    # Env specific

  roles:

    - name: "Developer Client | ALL | Basic applications & Env preferences"
      role: cmprescott.common

    - name: "Developer Client | SCM | SmartGit's Linux JRE dependency"
      role: cmprescott.jre 
      when: ansible_system == 'Linux'

    - name: "Developer Client | SCM | SmartGit"
      role: cmprescott.SmartGit

    - name: "Developer Client | Editor | SublimeText"
      sudo: Yes
      role: jdauphant.sublimetext

    - name: "Developer Client | Editor | SublimeText PackageControl"
      role: igor_mukhin.sublimetext3_packagecontrol
      packagecontrol_packages:
        - Ansible
        - AnsibleSnippets
        - Github Color Theme
        - GitHub Flavored Markdown Preview

...