---
# file: client.nfs.yml
#
# DESCRIPTION : Installs NFS mounts to fileserver for rtorrent.
# ANSIBLE VER : 2.0.
# TARGET OS   : Ubuntu 16.04
- name: "NFS Client"

  hosts: clients.nfs

  vars:

    # Host specific
    # -------------
    # nfs_server: CHANGEIT.net
    # nfs_path_movies: /home/CHANGEIT/Movies
    # nfs_path_tv: /home/CHANGEIT/media/TV
    # nfs_path_rtorrent: /home/CHANGEIT/rtorrent

    # Constants
    NFS_FSTYPE: "nfs,rw,bg,hard,intr,tcp,resvport"

    # NFS Client settings
    nfs_indirect_map_name: auto.nfs
    nfs_mount_path: /mnt/nfs

  pre_tasks:

    - name: "PreTask | ensure nfs client package(s) present"
      become: yes
      apt: name="{{ item }}"
      with_items:
        - rpcbind
        - nfs-common
      when: ansible_pkg_mgr == 'apt'

  roles:

    - name: "NFS | ensure automounts"
      become: yes
      role: ansible-role-autofs
      autofs_indirect_maps:
        - name: "{{ nfs_indirect_map_name }}"
          path: "{{ nfs_mount_path }}"
          mounts:
            - name: "{{ nfs_path_movies | basename }}"
              fstype: "{{ NFS_FSTYPE }}"
              url: "{{ nfs_server }}:{{ nfs_path_movies }}"
            - name: "{{ nfs_path_tv | basename }}"
              fstype: "{{ NFS_FSTYPE }}"
              url: "{{ nfs_server }}:{{ nfs_path_tv }}"
            - name: "{{ nfs_path_rtorrent | basename }}"
              fstype: "{{ NFS_FSTYPE }}"
              url: "{{ nfs_server }}:{{ nfs_path_rtorrent }}"

...
