---
# file: server.file.yml

- name: "FileSrv"

  hosts: servers.file

  vars:

    # Env specific
    path_mount_hd: /media/cp/4tb
    path_nfs_movies: /export/Movies
    path_nfs_tv: /export/TV
    path_nfs_music: /export/Music

    # Constants
    BIND_MOUNT_OPTS: "defaults,bind"
    BIND_MOUNT_FS: "none"
    NFS_OPTS: "*(rw,sync,no_root_squash)"

  roles:

    - name: "FileSrv | admin | ensure common apps/settings"
      role: cmprescott.common

    - name: "FileSrv | physical media | ensure mounts"
      role: MichaelRigart.mount
      sudo: yes
      mount_devices:
        - name: "{{ path_mount_hd }}"
          src: "/dev/sda1"
          fstype: ext4
          passno: 2

    - name: "FileSrv | bind | ensure mounts"
      role: MichaelRigart.mount
      sudo: yes
      mount_devices:
        - name: "{{ path_nfs_movies }}"
          src: "{{ path_mount_hd }}/Movies"
          opts: "{{ BIND_MOUNT_OPTS }}"
          fstype: "{{ BIND_MOUNT_FS }}"
        - name: "{{ path_nfs_tv }}"
          src: "{{ path_mount_hd }}/TV"
          opts: "{{ BIND_MOUNT_OPTS }}"
          fstype: "{{ BIND_MOUNT_FS }}"
        - name: "{{ path_nfs_music }}"
          src: "{{ path_mount_hd }}/Chris/Music/Singles"
          opts: "{{ BIND_MOUNT_OPTS }}"
          fstype: "{{ BIND_MOUNT_FS }}"

    - name: "FileSrv | share | ensure nfs from bind mounts"
      role: geerlingguy.nfs
      sudo: yes
      nfs_exports:
        - "{{ path_nfs_movies }} {{ NFS_OPTS }}"
        - "{{ path_nfs_music }} {{ NFS_OPTS }}"
        - "{{ path_nfs_tv }} {{ NFS_OPTS }}"

...