---
# file: server.torrent.yml
#
# DESCRIPTION : TODO
# ANSIBLE VER : 2.0.
# TARGET OS   : Ubuntu 14.04

- name: "Torrent Server"

  hosts: servers.torrent

  vars:

    # vars shared between roles
    php_fpm_listen: "/var/run/php5-fpm.sock"

  roles:

    - name: "Torrent | web interface | ensure ruTorrent"
      role: cmprescott.ruTorrent

    - name: "Torrent | web interface | ensure $PHP"
      role: geerlingguy.php
      become: yes
      php_packages:
        - php5-cli
        - php5-fpm
        - php5-geoip
      php_webserver_daemon: "nginx"
      php_enable_php_fpm: true

    - name: "Torrent | web interface | ensure Nginx"
      role: jdauphant.nginx
      become: yes
      nginx_http_params:
        - sendfile on
        - access_log /var/log/nginx/access.log
      nginx_sites:
        rutorrent:
          - listen 80
          - server_name localhost
          - root /var/www
          - location / { try_files $uri $uri/ =404; }
          - location ~ \.php$ { fastcgi_split_path_info ^(.+\.php)(/.+)$; fastcgi_pass unix:{{ php_fpm_listen }}; fastcgi_index index.php; include fastcgi_params; }
          - location /RPC2 { include scgi_params; scgi_pass 127.0.0.1:5000; }

...
